### ISSUE TITLE
Give more information

### ISSUE THREAD

**Issue by nimesha95** [xXZang3tsuXx/Node_Multicasting_Chat#1]
Unclear about what this does. Please give some more information in the readme. Thanks 😄 @xXZang3tsuXx

**Comment by xXZang3tsuXx** [comment]
In laymen terms its a replica of [this](https://socketio-chat-example.now.sh/)

**Comment by xXZang3tsuXx** [comment]
Yes but not with a back-end, which is why I called it a multi casting chat.
